/*
 * StressTestDlg.java
 *
 * Created on __DATE__, __TIME__
 */

package testtools;

import java.util.concurrent.atomic.AtomicLong;

;

/**
 *
 * @author  __USER__
 */
public class StressTestDlg extends javax.swing.JDialog implements Runnable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static long writestarttime = 0;
	public static long writestoptime = 0;
	public static AtomicLong writegpscount = new AtomicLong(0);
	public static AtomicLong delivercount = new AtomicLong(0);
	public static AtomicLong lastoktimes = new AtomicLong(0);
	public static AtomicLong lasterrortimes = new AtomicLong(0);
	public static AtomicLong historyoktimes = new AtomicLong(0);
	public static AtomicLong historyerrortimes = new AtomicLong(0);

	@Override
	//定时刷新状态
	public void run() {
		while (true) {
			try {
				Thread.sleep(1000);
				if (bstarttest) {
					writestoptime = System.currentTimeMillis();
				}
				long writetime = writestoptime - writestarttime;
				if (writetime <= 0)
					writetime = 1;
				String strStatus = String.format("GPS:%d(%d), Deliver:%d, Last:%d(%d), History:%d(%d)", writegpscount.get(), writegpscount.get() * 1000 / writetime, delivercount.get(), lastoktimes.get(), lasterrortimes.get(),
						historyoktimes.get(), historyerrortimes.get());
				this.textStatus.setText(strStatus);
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}

	/** Creates new form StressTestDlg */
	public StressTestDlg(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		bstarttest = false;
		bstartseat = false;
		wgps = null;
	}

	private boolean bstarttest;
	private boolean bstartseat;
	private WriteActiveMQGPS wgps;
	private WebSocketClientManager clientmanager;

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		label1 = new java.awt.Label();
		textCaller = new java.awt.TextField();
		label2 = new java.awt.Label();
		textCount = new java.awt.TextField();
		label3 = new java.awt.Label();
		textInterval = new java.awt.TextField();
		label4 = new java.awt.Label();
		textSeat = new java.awt.TextField();
		btnTest = new java.awt.Button();
		textStatus = new java.awt.TextField();
		btnSeat = new java.awt.Button();
		label5 = new java.awt.Label();
		textComCenter = new java.awt.TextField();
		btnTest1 = new java.awt.Button();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u901a\u4fe1\u4e2d\u5fc3\u538b\u529b\u6d4b\u8bd5");
		setAlwaysOnTop(true);
		setBackground(java.awt.Color.lightGray);
		setFont(new java.awt.Font("宋体", 0, 10));
		setModal(true);
		setName("stresstestdialog");

		label1.setFont(new java.awt.Font("宋体", 0, 12));
		label1.setText("CallLetter\uff1a");

		textCaller.setName("");
		textCaller.setText("28922819616");

		label2.setFont(new java.awt.Font("宋体", 0, 12));
		label2.setText("Count\uff1a");

		textCount.setName("");
		textCount.setText("102400");

		label3.setFont(new java.awt.Font("宋体", 0, 12));
		label3.setText("GPS Interval\uff1a");

		textInterval.setName("");
		textInterval.setText("10");

		label4.setFont(new java.awt.Font("宋体", 0, 12));
		label4.setText("Seat Count\uff1a");

		textSeat.setName("");
		textSeat.setText("20");

		btnTest.setFont(new java.awt.Font("宋体", 0, 12));
		btnTest.setLabel("Start GPS");
		btnTest.setName("");
		btnTest.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnTestActionPerformed(evt);
			}
		});

		textStatus.setEditable(false);
		textStatus.setName("");

		btnSeat.setFont(new java.awt.Font("宋体", 0, 12));
		btnSeat.setLabel("Start Seat");
		btnSeat.setName("");
		btnSeat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSeatActionPerformed(evt);
			}
		});

		label5.setFont(new java.awt.Font("宋体", 0, 12));
		label5.setText("ComCenter\uff1a");

		textComCenter.setName("");
		textComCenter.setText("192.110.10.164:8070");

		btnTest1.setFont(new java.awt.Font("宋体", 0, 12));
		btnTest1.setLabel("WriteUnitVersion");
		btnTest1.setName("");
		btnTest1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnTest1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(textStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(textCaller, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(textInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(textSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(textCount, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addComponent(textComCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)).addGap(19, 19, 19))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(142, 142, 142).addComponent(btnTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(27, 27, 27)
								.addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
								.addComponent(btnSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(72, 72, 72)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												layout.createSequentialGroup()
														.addGroup(
																layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(textCaller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(18, 18, 18)
														.addGroup(
																layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(textInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												layout.createSequentialGroup()
														.addGroup(
																layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(textCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(18, 18, 18)
														.addGroup(
																layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(textSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(19, 19, 19)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(textComCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(22, 22, 22)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(btnTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE).addComponent(textStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnTest1ActionPerformed(java.awt.event.ActionEvent evt) {
		WriteActiveMQUnitVersion wunitversion = new WriteActiveMQUnitVersion();
		wunitversion.start();
	}

	//
	private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {
		bstarttest = !bstarttest;
		if (bstarttest) {
			long callletter = Long.valueOf(this.textCaller.getText());
			int calllettercount = Integer.valueOf(this.textCount.getText());
			int gpsinterval = Integer.valueOf(this.textInterval.getText()) * 1000;
			wgps = new WriteActiveMQGPS(callletter, calllettercount, gpsinterval);
			writestarttime = System.currentTimeMillis();
			wgps.start();
			this.btnTest.setLabel("Stop GPS");
		} else {
			wgps.Stop();
			this.btnTest.setLabel("Start GPS");
			wgps = null;
		}
	}

	private void btnSeatActionPerformed(java.awt.event.ActionEvent evt) {
		bstartseat = !bstartseat;
		if (bstartseat) {
			long callletter = Long.valueOf(this.textCaller.getText());
			int calllettercount = Integer.valueOf(this.textCount.getText());
			int seatcount = Integer.valueOf(this.textSeat.getText());
			try {
				clientmanager = new WebSocketClientManager(textComCenter.getText(), seatcount);
				clientmanager.run(callletter, calllettercount);
			} catch (Exception e) {
				e.printStackTrace();
				if (clientmanager != null) {
					clientmanager.Stop();
					clientmanager = null;
				}
			}
			this.btnSeat.setLabel("Stop Seat");
		} else {
			this.btnSeat.setLabel("Start Seat");
			clientmanager.Stop();
			clientmanager = null;
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				StressTestDlg dialog = new StressTestDlg(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				Thread thread = new Thread(dialog, "StressTestStatus");
				thread.start();
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private java.awt.Button btnSeat;
	private java.awt.Button btnTest;
	private java.awt.Button btnTest1;
	private java.awt.Label label1;
	private java.awt.Label label2;
	private java.awt.Label label3;
	private java.awt.Label label4;
	private java.awt.Label label5;
	private java.awt.TextField textCaller;
	private java.awt.TextField textComCenter;
	private java.awt.TextField textCount;
	private java.awt.TextField textInterval;
	private java.awt.TextField textSeat;
	private java.awt.TextField textStatus;
	// End of variables declaration//GEN-END:variables
}