
package cc.chinagps.seat.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ivrPortType", targetNamespace = "http://ws.hsipcc.com")
//@XmlSeeAlso({
//    ObjectFactory.class
//})
public interface IvrPortType {


    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInvoice")
    @WebResult(name = "out", targetNamespace = "http://ws.hsipcc.com")
    @RequestWrapper(localName = "GetInvoice", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.GetInvoice")
    @ResponseWrapper(localName = "GetInvoiceResponse", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.GetInvoiceResponse")
    public String getInvoice(
        @WebParam(name = "in0", targetNamespace = "http://ws.hsipcc.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.hsipcc.com")
        String in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdatePassword")
    @WebResult(name = "out", targetNamespace = "http://ws.hsipcc.com")
    @RequestWrapper(localName = "UpdatePassword", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.UpdatePassword")
    @ResponseWrapper(localName = "UpdatePasswordResponse", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.UpdatePasswordResponse")
    public String updatePassword(
        @WebParam(name = "in0", targetNamespace = "http://ws.hsipcc.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.hsipcc.com")
        String in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddContactPhone")
    @WebResult(name = "out", targetNamespace = "http://ws.hsipcc.com")
    @RequestWrapper(localName = "AddContactPhone", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.AddContactPhone")
    @ResponseWrapper(localName = "AddContactPhoneResponse", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.AddContactPhoneResponse")
    public String addContactPhone(
        @WebParam(name = "in0", targetNamespace = "http://ws.hsipcc.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.hsipcc.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://ws.hsipcc.com")
        String in2);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetPhoneToAgent")
    @WebResult(name = "out", targetNamespace = "http://ws.hsipcc.com")
    @RequestWrapper(localName = "SetPhoneToAgent", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.SetPhoneToAgent")
    @ResponseWrapper(localName = "SetPhoneToAgentResponse", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.SetPhoneToAgentResponse")
    public String setPhoneToAgent(
        @WebParam(name = "in0", targetNamespace = "http://ws.hsipcc.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.hsipcc.com")
        String in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddNewBiz")
    @WebResult(name = "out", targetNamespace = "http://ws.hsipcc.com")
    @RequestWrapper(localName = "AddNewBiz", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.AddNewBiz")
    @ResponseWrapper(localName = "AddNewBizResponse", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.AddNewBizResponse")
    public String addNewBiz(
        @WebParam(name = "in0", targetNamespace = "http://ws.hsipcc.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.hsipcc.com")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPosition")
    @WebResult(name = "out", targetNamespace = "http://ws.hsipcc.com")
    @RequestWrapper(localName = "GetPosition", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.GetPosition")
    @ResponseWrapper(localName = "GetPositionResponse", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.GetPositionResponse")
    public String getPosition(
        @WebParam(name = "in0", targetNamespace = "http://ws.hsipcc.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAgentByPhone")
    @WebResult(name = "out", targetNamespace = "http://ws.hsipcc.com")
    @RequestWrapper(localName = "GetAgentByPhone", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.GetAgentByPhone")
    @ResponseWrapper(localName = "GetAgentByPhoneResponse", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.GetAgentByPhoneResponse")
    public String getAgentByPhone(
        @WebParam(name = "in0", targetNamespace = "http://ws.hsipcc.com")
        String in0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://ws.hsipcc.com")
    @RequestWrapper(localName = "callWebService", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.CallWebService")
    @ResponseWrapper(localName = "callWebServiceResponse", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.CallWebServiceResponse")
    public String callWebService();

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckCust")
    @WebResult(name = "out", targetNamespace = "http://ws.hsipcc.com")
    @RequestWrapper(localName = "CheckCust", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.CheckCust")
    @ResponseWrapper(localName = "CheckCustResponse", targetNamespace = "http://ws.hsipcc.com", className = "cc.chinagps.seat.service.CheckCustResponse")
    public String checkCust(
        @WebParam(name = "in0", targetNamespace = "http://ws.hsipcc.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.hsipcc.com")
        String in1);

}
