// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fault.proto

package hbase;

public final class FaultDataBuff {
  private FaultDataBuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FaultDefineOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 faultType = 1;
    /**
     * <code>optional int32 faultType = 1;</code>
     *
     * <pre>
     *故障类别
     * </pre>
     */
    boolean hasFaultType();
    /**
     * <code>optional int32 faultType = 1;</code>
     *
     * <pre>
     *故障类别
     * </pre>
     */
    int getFaultType();

    // repeated string faultCode = 2;
    /**
     * <code>repeated string faultCode = 2;</code>
     *
     * <pre>
     *故障码
     * </pre>
     */
    java.util.List<java.lang.String>
    getFaultCodeList();
    /**
     * <code>repeated string faultCode = 2;</code>
     *
     * <pre>
     *故障码
     * </pre>
     */
    int getFaultCodeCount();
    /**
     * <code>repeated string faultCode = 2;</code>
     *
     * <pre>
     *故障码
     * </pre>
     */
    java.lang.String getFaultCode(int index);
    /**
     * <code>repeated string faultCode = 2;</code>
     *
     * <pre>
     *故障码
     * </pre>
     */
    com.google.protobuf.ByteString
        getFaultCodeBytes(int index);
  }
  /**
   * Protobuf type {@code gboss.FaultDefine}
   *
   * <pre>
   **
   *  模块故障信息(OBD)
   * </pre>
   */
  public static final class FaultDefine extends
      com.google.protobuf.GeneratedMessage
      implements FaultDefineOrBuilder {
    // Use FaultDefine.newBuilder() to construct.
    private FaultDefine(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FaultDefine(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FaultDefine defaultInstance;
    public static FaultDefine getDefaultInstance() {
      return defaultInstance;
    }

    public FaultDefine getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FaultDefine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              faultType_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                faultCode_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              faultCode_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          faultCode_ = new com.google.protobuf.UnmodifiableLazyStringList(faultCode_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hbase.FaultDataBuff.internal_static_gboss_FaultDefine_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hbase.FaultDataBuff.internal_static_gboss_FaultDefine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hbase.FaultDataBuff.FaultDefine.class, hbase.FaultDataBuff.FaultDefine.Builder.class);
    }

    public static com.google.protobuf.Parser<FaultDefine> PARSER =
        new com.google.protobuf.AbstractParser<FaultDefine>() {
      public FaultDefine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FaultDefine(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FaultDefine> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 faultType = 1;
    public static final int FAULTTYPE_FIELD_NUMBER = 1;
    private int faultType_;
    /**
     * <code>optional int32 faultType = 1;</code>
     *
     * <pre>
     *故障类别
     * </pre>
     */
    public boolean hasFaultType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 faultType = 1;</code>
     *
     * <pre>
     *故障类别
     * </pre>
     */
    public int getFaultType() {
      return faultType_;
    }

    // repeated string faultCode = 2;
    public static final int FAULTCODE_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList faultCode_;
    /**
     * <code>repeated string faultCode = 2;</code>
     *
     * <pre>
     *故障码
     * </pre>
     */
    public java.util.List<java.lang.String>
        getFaultCodeList() {
      return faultCode_;
    }
    /**
     * <code>repeated string faultCode = 2;</code>
     *
     * <pre>
     *故障码
     * </pre>
     */
    public int getFaultCodeCount() {
      return faultCode_.size();
    }
    /**
     * <code>repeated string faultCode = 2;</code>
     *
     * <pre>
     *故障码
     * </pre>
     */
    public java.lang.String getFaultCode(int index) {
      return faultCode_.get(index);
    }
    /**
     * <code>repeated string faultCode = 2;</code>
     *
     * <pre>
     *故障码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFaultCodeBytes(int index) {
      return faultCode_.getByteString(index);
    }

    private void initFields() {
      faultType_ = 0;
      faultCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, faultType_);
      }
      for (int i = 0; i < faultCode_.size(); i++) {
        output.writeBytes(2, faultCode_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, faultType_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < faultCode_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(faultCode_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFaultCodeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hbase.FaultDataBuff.FaultDefine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hbase.FaultDataBuff.FaultDefine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hbase.FaultDataBuff.FaultDefine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hbase.FaultDataBuff.FaultDefine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hbase.FaultDataBuff.FaultDefine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hbase.FaultDataBuff.FaultDefine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hbase.FaultDataBuff.FaultDefine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hbase.FaultDataBuff.FaultDefine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hbase.FaultDataBuff.FaultDefine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hbase.FaultDataBuff.FaultDefine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hbase.FaultDataBuff.FaultDefine prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gboss.FaultDefine}
     *
     * <pre>
     **
     *  模块故障信息(OBD)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hbase.FaultDataBuff.FaultDefineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hbase.FaultDataBuff.internal_static_gboss_FaultDefine_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hbase.FaultDataBuff.internal_static_gboss_FaultDefine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hbase.FaultDataBuff.FaultDefine.class, hbase.FaultDataBuff.FaultDefine.Builder.class);
      }

      // Construct using hbase.FaultDataBuff.FaultDefine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        faultType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        faultCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hbase.FaultDataBuff.internal_static_gboss_FaultDefine_descriptor;
      }

      public hbase.FaultDataBuff.FaultDefine getDefaultInstanceForType() {
        return hbase.FaultDataBuff.FaultDefine.getDefaultInstance();
      }

      public hbase.FaultDataBuff.FaultDefine build() {
        hbase.FaultDataBuff.FaultDefine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hbase.FaultDataBuff.FaultDefine buildPartial() {
        hbase.FaultDataBuff.FaultDefine result = new hbase.FaultDataBuff.FaultDefine(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.faultType_ = faultType_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          faultCode_ = new com.google.protobuf.UnmodifiableLazyStringList(
              faultCode_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.faultCode_ = faultCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hbase.FaultDataBuff.FaultDefine) {
          return mergeFrom((hbase.FaultDataBuff.FaultDefine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hbase.FaultDataBuff.FaultDefine other) {
        if (other == hbase.FaultDataBuff.FaultDefine.getDefaultInstance()) return this;
        if (other.hasFaultType()) {
          setFaultType(other.getFaultType());
        }
        if (!other.faultCode_.isEmpty()) {
          if (faultCode_.isEmpty()) {
            faultCode_ = other.faultCode_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFaultCodeIsMutable();
            faultCode_.addAll(other.faultCode_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hbase.FaultDataBuff.FaultDefine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hbase.FaultDataBuff.FaultDefine) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 faultType = 1;
      private int faultType_ ;
      /**
       * <code>optional int32 faultType = 1;</code>
       *
       * <pre>
       *故障类别
       * </pre>
       */
      public boolean hasFaultType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 faultType = 1;</code>
       *
       * <pre>
       *故障类别
       * </pre>
       */
      public int getFaultType() {
        return faultType_;
      }
      /**
       * <code>optional int32 faultType = 1;</code>
       *
       * <pre>
       *故障类别
       * </pre>
       */
      public Builder setFaultType(int value) {
        bitField0_ |= 0x00000001;
        faultType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 faultType = 1;</code>
       *
       * <pre>
       *故障类别
       * </pre>
       */
      public Builder clearFaultType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        faultType_ = 0;
        onChanged();
        return this;
      }

      // repeated string faultCode = 2;
      private com.google.protobuf.LazyStringList faultCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFaultCodeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          faultCode_ = new com.google.protobuf.LazyStringArrayList(faultCode_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string faultCode = 2;</code>
       *
       * <pre>
       *故障码
       * </pre>
       */
      public java.util.List<java.lang.String>
          getFaultCodeList() {
        return java.util.Collections.unmodifiableList(faultCode_);
      }
      /**
       * <code>repeated string faultCode = 2;</code>
       *
       * <pre>
       *故障码
       * </pre>
       */
      public int getFaultCodeCount() {
        return faultCode_.size();
      }
      /**
       * <code>repeated string faultCode = 2;</code>
       *
       * <pre>
       *故障码
       * </pre>
       */
      public java.lang.String getFaultCode(int index) {
        return faultCode_.get(index);
      }
      /**
       * <code>repeated string faultCode = 2;</code>
       *
       * <pre>
       *故障码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFaultCodeBytes(int index) {
        return faultCode_.getByteString(index);
      }
      /**
       * <code>repeated string faultCode = 2;</code>
       *
       * <pre>
       *故障码
       * </pre>
       */
      public Builder setFaultCode(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFaultCodeIsMutable();
        faultCode_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string faultCode = 2;</code>
       *
       * <pre>
       *故障码
       * </pre>
       */
      public Builder addFaultCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFaultCodeIsMutable();
        faultCode_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string faultCode = 2;</code>
       *
       * <pre>
       *故障码
       * </pre>
       */
      public Builder addAllFaultCode(
          java.lang.Iterable<java.lang.String> values) {
        ensureFaultCodeIsMutable();
        super.addAll(values, faultCode_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string faultCode = 2;</code>
       *
       * <pre>
       *故障码
       * </pre>
       */
      public Builder clearFaultCode() {
        faultCode_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string faultCode = 2;</code>
       *
       * <pre>
       *故障码
       * </pre>
       */
      public Builder addFaultCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFaultCodeIsMutable();
        faultCode_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gboss.FaultDefine)
    }

    static {
      defaultInstance = new FaultDefine(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gboss.FaultDefine)
  }

  public interface FaultInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string callLetter = 1;
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车辆呼号
     * </pre>
     */
    boolean hasCallLetter();
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车辆呼号
     * </pre>
     */
    java.lang.String getCallLetter();
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车辆呼号
     * </pre>
     */
    com.google.protobuf.ByteString
        getCallLetterBytes();

    // required int64 faultTime = 2;
    /**
     * <code>required int64 faultTime = 2;</code>
     *
     * <pre>
     *故障时间(从1970-1-1 0:0:0开始的秒数，格林威治时间), 为了提高处理速度,不用字符串
     * </pre>
     */
    boolean hasFaultTime();
    /**
     * <code>required int64 faultTime = 2;</code>
     *
     * <pre>
     *故障时间(从1970-1-1 0:0:0开始的秒数，格林威治时间), 为了提高处理速度,不用字符串
     * </pre>
     */
    long getFaultTime();

    // repeated .gboss.FaultDefine faults = 3;
    /**
     * <code>repeated .gboss.FaultDefine faults = 3;</code>
     *
     * <pre>
     *新的分类故障码
     * </pre>
     */
    java.util.List<hbase.FaultDataBuff.FaultDefine> 
        getFaultsList();
    /**
     * <code>repeated .gboss.FaultDefine faults = 3;</code>
     *
     * <pre>
     *新的分类故障码
     * </pre>
     */
    hbase.FaultDataBuff.FaultDefine getFaults(int index);
    /**
     * <code>repeated .gboss.FaultDefine faults = 3;</code>
     *
     * <pre>
     *新的分类故障码
     * </pre>
     */
    int getFaultsCount();
    /**
     * <code>repeated .gboss.FaultDefine faults = 3;</code>
     *
     * <pre>
     *新的分类故障码
     * </pre>
     */
    java.util.List<? extends hbase.FaultDataBuff.FaultDefineOrBuilder> 
        getFaultsOrBuilderList();
    /**
     * <code>repeated .gboss.FaultDefine faults = 3;</code>
     *
     * <pre>
     *新的分类故障码
     * </pre>
     */
    hbase.FaultDataBuff.FaultDefineOrBuilder getFaultsOrBuilder(
        int index);

    // optional int32 unitType = 4;
    /**
     * <code>optional int32 unitType = 4;</code>
     *
     * <pre>
     *终端协议类型
     * </pre>
     */
    boolean hasUnitType();
    /**
     * <code>optional int32 unitType = 4;</code>
     *
     * <pre>
     *终端协议类型
     * </pre>
     */
    int getUnitType();

    // optional int32 history = 5;
    /**
     * <code>optional int32 history = 5;</code>
     *
     * <pre>
     *是否是黑匣子记录（0、或不存在表示是实时GPS，1:表示是黑匣子记录, 2:表示盲点补传）
     * </pre>
     */
    boolean hasHistory();
    /**
     * <code>optional int32 history = 5;</code>
     *
     * <pre>
     *是否是黑匣子记录（0、或不存在表示是实时GPS，1:表示是黑匣子记录, 2:表示盲点补传）
     * </pre>
     */
    int getHistory();
  }
  /**
   * Protobuf type {@code gboss.FaultInfo}
   */
  public static final class FaultInfo extends
      com.google.protobuf.GeneratedMessage
      implements FaultInfoOrBuilder {
    // Use FaultInfo.newBuilder() to construct.
    private FaultInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FaultInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FaultInfo defaultInstance;
    public static FaultInfo getDefaultInstance() {
      return defaultInstance;
    }

    public FaultInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FaultInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              callLetter_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              faultTime_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                faults_ = new java.util.ArrayList<hbase.FaultDataBuff.FaultDefine>();
                mutable_bitField0_ |= 0x00000004;
              }
              faults_.add(input.readMessage(hbase.FaultDataBuff.FaultDefine.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              unitType_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              history_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          faults_ = java.util.Collections.unmodifiableList(faults_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hbase.FaultDataBuff.internal_static_gboss_FaultInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hbase.FaultDataBuff.internal_static_gboss_FaultInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hbase.FaultDataBuff.FaultInfo.class, hbase.FaultDataBuff.FaultInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<FaultInfo> PARSER =
        new com.google.protobuf.AbstractParser<FaultInfo>() {
      public FaultInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FaultInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FaultInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string callLetter = 1;
    public static final int CALLLETTER_FIELD_NUMBER = 1;
    private java.lang.Object callLetter_;
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车辆呼号
     * </pre>
     */
    public boolean hasCallLetter() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车辆呼号
     * </pre>
     */
    public java.lang.String getCallLetter() {
      java.lang.Object ref = callLetter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          callLetter_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车辆呼号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCallLetterBytes() {
      java.lang.Object ref = callLetter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callLetter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 faultTime = 2;
    public static final int FAULTTIME_FIELD_NUMBER = 2;
    private long faultTime_;
    /**
     * <code>required int64 faultTime = 2;</code>
     *
     * <pre>
     *故障时间(从1970-1-1 0:0:0开始的秒数，格林威治时间), 为了提高处理速度,不用字符串
     * </pre>
     */
    public boolean hasFaultTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 faultTime = 2;</code>
     *
     * <pre>
     *故障时间(从1970-1-1 0:0:0开始的秒数，格林威治时间), 为了提高处理速度,不用字符串
     * </pre>
     */
    public long getFaultTime() {
      return faultTime_;
    }

    // repeated .gboss.FaultDefine faults = 3;
    public static final int FAULTS_FIELD_NUMBER = 3;
    private java.util.List<hbase.FaultDataBuff.FaultDefine> faults_;
    /**
     * <code>repeated .gboss.FaultDefine faults = 3;</code>
     *
     * <pre>
     *新的分类故障码
     * </pre>
     */
    public java.util.List<hbase.FaultDataBuff.FaultDefine> getFaultsList() {
      return faults_;
    }
    /**
     * <code>repeated .gboss.FaultDefine faults = 3;</code>
     *
     * <pre>
     *新的分类故障码
     * </pre>
     */
    public java.util.List<? extends hbase.FaultDataBuff.FaultDefineOrBuilder> 
        getFaultsOrBuilderList() {
      return faults_;
    }
    /**
     * <code>repeated .gboss.FaultDefine faults = 3;</code>
     *
     * <pre>
     *新的分类故障码
     * </pre>
     */
    public int getFaultsCount() {
      return faults_.size();
    }
    /**
     * <code>repeated .gboss.FaultDefine faults = 3;</code>
     *
     * <pre>
     *新的分类故障码
     * </pre>
     */
    public hbase.FaultDataBuff.FaultDefine getFaults(int index) {
      return faults_.get(index);
    }
    /**
     * <code>repeated .gboss.FaultDefine faults = 3;</code>
     *
     * <pre>
     *新的分类故障码
     * </pre>
     */
    public hbase.FaultDataBuff.FaultDefineOrBuilder getFaultsOrBuilder(
        int index) {
      return faults_.get(index);
    }

    // optional int32 unitType = 4;
    public static final int UNITTYPE_FIELD_NUMBER = 4;
    private int unitType_;
    /**
     * <code>optional int32 unitType = 4;</code>
     *
     * <pre>
     *终端协议类型
     * </pre>
     */
    public boolean hasUnitType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 unitType = 4;</code>
     *
     * <pre>
     *终端协议类型
     * </pre>
     */
    public int getUnitType() {
      return unitType_;
    }

    // optional int32 history = 5;
    public static final int HISTORY_FIELD_NUMBER = 5;
    private int history_;
    /**
     * <code>optional int32 history = 5;</code>
     *
     * <pre>
     *是否是黑匣子记录（0、或不存在表示是实时GPS，1:表示是黑匣子记录, 2:表示盲点补传）
     * </pre>
     */
    public boolean hasHistory() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 history = 5;</code>
     *
     * <pre>
     *是否是黑匣子记录（0、或不存在表示是实时GPS，1:表示是黑匣子记录, 2:表示盲点补传）
     * </pre>
     */
    public int getHistory() {
      return history_;
    }

    private void initFields() {
      callLetter_ = "";
      faultTime_ = 0L;
      faults_ = java.util.Collections.emptyList();
      unitType_ = 0;
      history_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCallLetter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFaultTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCallLetterBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, faultTime_);
      }
      for (int i = 0; i < faults_.size(); i++) {
        output.writeMessage(3, faults_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, unitType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, history_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCallLetterBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, faultTime_);
      }
      for (int i = 0; i < faults_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, faults_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, unitType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, history_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hbase.FaultDataBuff.FaultInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hbase.FaultDataBuff.FaultInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hbase.FaultDataBuff.FaultInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hbase.FaultDataBuff.FaultInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hbase.FaultDataBuff.FaultInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hbase.FaultDataBuff.FaultInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hbase.FaultDataBuff.FaultInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hbase.FaultDataBuff.FaultInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hbase.FaultDataBuff.FaultInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hbase.FaultDataBuff.FaultInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hbase.FaultDataBuff.FaultInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gboss.FaultInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hbase.FaultDataBuff.FaultInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hbase.FaultDataBuff.internal_static_gboss_FaultInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hbase.FaultDataBuff.internal_static_gboss_FaultInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hbase.FaultDataBuff.FaultInfo.class, hbase.FaultDataBuff.FaultInfo.Builder.class);
      }

      // Construct using hbase.FaultDataBuff.FaultInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFaultsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        callLetter_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        faultTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (faultsBuilder_ == null) {
          faults_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          faultsBuilder_.clear();
        }
        unitType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        history_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hbase.FaultDataBuff.internal_static_gboss_FaultInfo_descriptor;
      }

      public hbase.FaultDataBuff.FaultInfo getDefaultInstanceForType() {
        return hbase.FaultDataBuff.FaultInfo.getDefaultInstance();
      }

      public hbase.FaultDataBuff.FaultInfo build() {
        hbase.FaultDataBuff.FaultInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hbase.FaultDataBuff.FaultInfo buildPartial() {
        hbase.FaultDataBuff.FaultInfo result = new hbase.FaultDataBuff.FaultInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.callLetter_ = callLetter_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.faultTime_ = faultTime_;
        if (faultsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            faults_ = java.util.Collections.unmodifiableList(faults_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.faults_ = faults_;
        } else {
          result.faults_ = faultsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.unitType_ = unitType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.history_ = history_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hbase.FaultDataBuff.FaultInfo) {
          return mergeFrom((hbase.FaultDataBuff.FaultInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hbase.FaultDataBuff.FaultInfo other) {
        if (other == hbase.FaultDataBuff.FaultInfo.getDefaultInstance()) return this;
        if (other.hasCallLetter()) {
          bitField0_ |= 0x00000001;
          callLetter_ = other.callLetter_;
          onChanged();
        }
        if (other.hasFaultTime()) {
          setFaultTime(other.getFaultTime());
        }
        if (faultsBuilder_ == null) {
          if (!other.faults_.isEmpty()) {
            if (faults_.isEmpty()) {
              faults_ = other.faults_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureFaultsIsMutable();
              faults_.addAll(other.faults_);
            }
            onChanged();
          }
        } else {
          if (!other.faults_.isEmpty()) {
            if (faultsBuilder_.isEmpty()) {
              faultsBuilder_.dispose();
              faultsBuilder_ = null;
              faults_ = other.faults_;
              bitField0_ = (bitField0_ & ~0x00000004);
              faultsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFaultsFieldBuilder() : null;
            } else {
              faultsBuilder_.addAllMessages(other.faults_);
            }
          }
        }
        if (other.hasUnitType()) {
          setUnitType(other.getUnitType());
        }
        if (other.hasHistory()) {
          setHistory(other.getHistory());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCallLetter()) {
          
          return false;
        }
        if (!hasFaultTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hbase.FaultDataBuff.FaultInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hbase.FaultDataBuff.FaultInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string callLetter = 1;
      private java.lang.Object callLetter_ = "";
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车辆呼号
       * </pre>
       */
      public boolean hasCallLetter() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车辆呼号
       * </pre>
       */
      public java.lang.String getCallLetter() {
        java.lang.Object ref = callLetter_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          callLetter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车辆呼号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCallLetterBytes() {
        java.lang.Object ref = callLetter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          callLetter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车辆呼号
       * </pre>
       */
      public Builder setCallLetter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        callLetter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车辆呼号
       * </pre>
       */
      public Builder clearCallLetter() {
        bitField0_ = (bitField0_ & ~0x00000001);
        callLetter_ = getDefaultInstance().getCallLetter();
        onChanged();
        return this;
      }
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车辆呼号
       * </pre>
       */
      public Builder setCallLetterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        callLetter_ = value;
        onChanged();
        return this;
      }

      // required int64 faultTime = 2;
      private long faultTime_ ;
      /**
       * <code>required int64 faultTime = 2;</code>
       *
       * <pre>
       *故障时间(从1970-1-1 0:0:0开始的秒数，格林威治时间), 为了提高处理速度,不用字符串
       * </pre>
       */
      public boolean hasFaultTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 faultTime = 2;</code>
       *
       * <pre>
       *故障时间(从1970-1-1 0:0:0开始的秒数，格林威治时间), 为了提高处理速度,不用字符串
       * </pre>
       */
      public long getFaultTime() {
        return faultTime_;
      }
      /**
       * <code>required int64 faultTime = 2;</code>
       *
       * <pre>
       *故障时间(从1970-1-1 0:0:0开始的秒数，格林威治时间), 为了提高处理速度,不用字符串
       * </pre>
       */
      public Builder setFaultTime(long value) {
        bitField0_ |= 0x00000002;
        faultTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 faultTime = 2;</code>
       *
       * <pre>
       *故障时间(从1970-1-1 0:0:0开始的秒数，格林威治时间), 为了提高处理速度,不用字符串
       * </pre>
       */
      public Builder clearFaultTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        faultTime_ = 0L;
        onChanged();
        return this;
      }

      // repeated .gboss.FaultDefine faults = 3;
      private java.util.List<hbase.FaultDataBuff.FaultDefine> faults_ =
        java.util.Collections.emptyList();
      private void ensureFaultsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          faults_ = new java.util.ArrayList<hbase.FaultDataBuff.FaultDefine>(faults_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          hbase.FaultDataBuff.FaultDefine, hbase.FaultDataBuff.FaultDefine.Builder, hbase.FaultDataBuff.FaultDefineOrBuilder> faultsBuilder_;

      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public java.util.List<hbase.FaultDataBuff.FaultDefine> getFaultsList() {
        if (faultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(faults_);
        } else {
          return faultsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public int getFaultsCount() {
        if (faultsBuilder_ == null) {
          return faults_.size();
        } else {
          return faultsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public hbase.FaultDataBuff.FaultDefine getFaults(int index) {
        if (faultsBuilder_ == null) {
          return faults_.get(index);
        } else {
          return faultsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public Builder setFaults(
          int index, hbase.FaultDataBuff.FaultDefine value) {
        if (faultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFaultsIsMutable();
          faults_.set(index, value);
          onChanged();
        } else {
          faultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public Builder setFaults(
          int index, hbase.FaultDataBuff.FaultDefine.Builder builderForValue) {
        if (faultsBuilder_ == null) {
          ensureFaultsIsMutable();
          faults_.set(index, builderForValue.build());
          onChanged();
        } else {
          faultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public Builder addFaults(hbase.FaultDataBuff.FaultDefine value) {
        if (faultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFaultsIsMutable();
          faults_.add(value);
          onChanged();
        } else {
          faultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public Builder addFaults(
          int index, hbase.FaultDataBuff.FaultDefine value) {
        if (faultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFaultsIsMutable();
          faults_.add(index, value);
          onChanged();
        } else {
          faultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public Builder addFaults(
          hbase.FaultDataBuff.FaultDefine.Builder builderForValue) {
        if (faultsBuilder_ == null) {
          ensureFaultsIsMutable();
          faults_.add(builderForValue.build());
          onChanged();
        } else {
          faultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public Builder addFaults(
          int index, hbase.FaultDataBuff.FaultDefine.Builder builderForValue) {
        if (faultsBuilder_ == null) {
          ensureFaultsIsMutable();
          faults_.add(index, builderForValue.build());
          onChanged();
        } else {
          faultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public Builder addAllFaults(
          java.lang.Iterable<? extends hbase.FaultDataBuff.FaultDefine> values) {
        if (faultsBuilder_ == null) {
          ensureFaultsIsMutable();
          super.addAll(values, faults_);
          onChanged();
        } else {
          faultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public Builder clearFaults() {
        if (faultsBuilder_ == null) {
          faults_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          faultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public Builder removeFaults(int index) {
        if (faultsBuilder_ == null) {
          ensureFaultsIsMutable();
          faults_.remove(index);
          onChanged();
        } else {
          faultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public hbase.FaultDataBuff.FaultDefine.Builder getFaultsBuilder(
          int index) {
        return getFaultsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public hbase.FaultDataBuff.FaultDefineOrBuilder getFaultsOrBuilder(
          int index) {
        if (faultsBuilder_ == null) {
          return faults_.get(index);  } else {
          return faultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public java.util.List<? extends hbase.FaultDataBuff.FaultDefineOrBuilder> 
           getFaultsOrBuilderList() {
        if (faultsBuilder_ != null) {
          return faultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(faults_);
        }
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public hbase.FaultDataBuff.FaultDefine.Builder addFaultsBuilder() {
        return getFaultsFieldBuilder().addBuilder(
            hbase.FaultDataBuff.FaultDefine.getDefaultInstance());
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public hbase.FaultDataBuff.FaultDefine.Builder addFaultsBuilder(
          int index) {
        return getFaultsFieldBuilder().addBuilder(
            index, hbase.FaultDataBuff.FaultDefine.getDefaultInstance());
      }
      /**
       * <code>repeated .gboss.FaultDefine faults = 3;</code>
       *
       * <pre>
       *新的分类故障码
       * </pre>
       */
      public java.util.List<hbase.FaultDataBuff.FaultDefine.Builder> 
           getFaultsBuilderList() {
        return getFaultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          hbase.FaultDataBuff.FaultDefine, hbase.FaultDataBuff.FaultDefine.Builder, hbase.FaultDataBuff.FaultDefineOrBuilder> 
          getFaultsFieldBuilder() {
        if (faultsBuilder_ == null) {
          faultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              hbase.FaultDataBuff.FaultDefine, hbase.FaultDataBuff.FaultDefine.Builder, hbase.FaultDataBuff.FaultDefineOrBuilder>(
                  faults_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          faults_ = null;
        }
        return faultsBuilder_;
      }

      // optional int32 unitType = 4;
      private int unitType_ ;
      /**
       * <code>optional int32 unitType = 4;</code>
       *
       * <pre>
       *终端协议类型
       * </pre>
       */
      public boolean hasUnitType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 unitType = 4;</code>
       *
       * <pre>
       *终端协议类型
       * </pre>
       */
      public int getUnitType() {
        return unitType_;
      }
      /**
       * <code>optional int32 unitType = 4;</code>
       *
       * <pre>
       *终端协议类型
       * </pre>
       */
      public Builder setUnitType(int value) {
        bitField0_ |= 0x00000008;
        unitType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 unitType = 4;</code>
       *
       * <pre>
       *终端协议类型
       * </pre>
       */
      public Builder clearUnitType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        unitType_ = 0;
        onChanged();
        return this;
      }

      // optional int32 history = 5;
      private int history_ ;
      /**
       * <code>optional int32 history = 5;</code>
       *
       * <pre>
       *是否是黑匣子记录（0、或不存在表示是实时GPS，1:表示是黑匣子记录, 2:表示盲点补传）
       * </pre>
       */
      public boolean hasHistory() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 history = 5;</code>
       *
       * <pre>
       *是否是黑匣子记录（0、或不存在表示是实时GPS，1:表示是黑匣子记录, 2:表示盲点补传）
       * </pre>
       */
      public int getHistory() {
        return history_;
      }
      /**
       * <code>optional int32 history = 5;</code>
       *
       * <pre>
       *是否是黑匣子记录（0、或不存在表示是实时GPS，1:表示是黑匣子记录, 2:表示盲点补传）
       * </pre>
       */
      public Builder setHistory(int value) {
        bitField0_ |= 0x00000010;
        history_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 history = 5;</code>
       *
       * <pre>
       *是否是黑匣子记录（0、或不存在表示是实时GPS，1:表示是黑匣子记录, 2:表示盲点补传）
       * </pre>
       */
      public Builder clearHistory() {
        bitField0_ = (bitField0_ & ~0x00000010);
        history_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gboss.FaultInfo)
    }

    static {
      defaultInstance = new FaultInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gboss.FaultInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gboss_FaultDefine_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gboss_FaultDefine_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gboss_FaultInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gboss_FaultInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Fault.proto\022\005gboss\"3\n\013FaultDefine\022\021\n\tf" +
      "aultType\030\001 \001(\005\022\021\n\tfaultCode\030\002 \003(\t\"y\n\tFau" +
      "ltInfo\022\022\n\ncallLetter\030\001 \002(\t\022\021\n\tfaultTime\030" +
      "\002 \002(\003\022\"\n\006faults\030\003 \003(\0132\022.gboss.FaultDefin" +
      "e\022\020\n\010unitType\030\004 \001(\005\022\017\n\007history\030\005 \001(\005B\026\n\005" +
      "hbaseB\rFaultDataBuff"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gboss_FaultDefine_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gboss_FaultDefine_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gboss_FaultDefine_descriptor,
              new java.lang.String[] { "FaultType", "FaultCode", });
          internal_static_gboss_FaultInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_gboss_FaultInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gboss_FaultInfo_descriptor,
              new java.lang.String[] { "CallLetter", "FaultTime", "Faults", "UnitType", "History", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
