// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InnerData.proto

package cc.chinagps.gateway.buff;

public final class InnerDataBuff {
  private InnerDataBuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UnitsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string callLetters = 1;
    /**
     * <code>repeated string callLetters = 1;</code>
     *
     * <pre>
     *车辆列表
     * </pre>
     */
    java.util.List<java.lang.String>
    getCallLettersList();
    /**
     * <code>repeated string callLetters = 1;</code>
     *
     * <pre>
     *车辆列表
     * </pre>
     */
    int getCallLettersCount();
    /**
     * <code>repeated string callLetters = 1;</code>
     *
     * <pre>
     *车辆列表
     * </pre>
     */
    java.lang.String getCallLetters(int index);
    /**
     * <code>repeated string callLetters = 1;</code>
     *
     * <pre>
     *车辆列表
     * </pre>
     */
    com.google.protobuf.ByteString
        getCallLettersBytes(int index);
  }
  /**
   * Protobuf type {@code seggateway.Units}
   *
   * <pre>
   **
   *  车辆列表
   * </pre>
   */
  public static final class Units extends
      com.google.protobuf.GeneratedMessage
      implements UnitsOrBuilder {
    // Use Units.newBuilder() to construct.
    private Units(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Units(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Units defaultInstance;
    public static Units getDefaultInstance() {
      return defaultInstance;
    }

    public Units getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Units(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                callLetters_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              callLetters_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          callLetters_ = new com.google.protobuf.UnmodifiableLazyStringList(callLetters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Units_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Units_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.chinagps.gateway.buff.InnerDataBuff.Units.class, cc.chinagps.gateway.buff.InnerDataBuff.Units.Builder.class);
    }

    public static com.google.protobuf.Parser<Units> PARSER =
        new com.google.protobuf.AbstractParser<Units>() {
      public Units parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Units(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Units> getParserForType() {
      return PARSER;
    }

    // repeated string callLetters = 1;
    public static final int CALLLETTERS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList callLetters_;
    /**
     * <code>repeated string callLetters = 1;</code>
     *
     * <pre>
     *车辆列表
     * </pre>
     */
    public java.util.List<java.lang.String>
        getCallLettersList() {
      return callLetters_;
    }
    /**
     * <code>repeated string callLetters = 1;</code>
     *
     * <pre>
     *车辆列表
     * </pre>
     */
    public int getCallLettersCount() {
      return callLetters_.size();
    }
    /**
     * <code>repeated string callLetters = 1;</code>
     *
     * <pre>
     *车辆列表
     * </pre>
     */
    public java.lang.String getCallLetters(int index) {
      return callLetters_.get(index);
    }
    /**
     * <code>repeated string callLetters = 1;</code>
     *
     * <pre>
     *车辆列表
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCallLettersBytes(int index) {
      return callLetters_.getByteString(index);
    }

    private void initFields() {
      callLetters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < callLetters_.size(); i++) {
        output.writeBytes(1, callLetters_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < callLetters_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(callLetters_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCallLettersList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.chinagps.gateway.buff.InnerDataBuff.Units parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Units parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Units parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Units parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Units parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Units parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Units parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Units parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Units parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Units parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.chinagps.gateway.buff.InnerDataBuff.Units prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code seggateway.Units}
     *
     * <pre>
     **
     *  车辆列表
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cc.chinagps.gateway.buff.InnerDataBuff.UnitsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Units_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Units_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.chinagps.gateway.buff.InnerDataBuff.Units.class, cc.chinagps.gateway.buff.InnerDataBuff.Units.Builder.class);
      }

      // Construct using cc.chinagps.gateway.buff.InnerDataBuff.Units.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        callLetters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Units_descriptor;
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.Units getDefaultInstanceForType() {
        return cc.chinagps.gateway.buff.InnerDataBuff.Units.getDefaultInstance();
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.Units build() {
        cc.chinagps.gateway.buff.InnerDataBuff.Units result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.Units buildPartial() {
        cc.chinagps.gateway.buff.InnerDataBuff.Units result = new cc.chinagps.gateway.buff.InnerDataBuff.Units(this);
        //int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          callLetters_ = new com.google.protobuf.UnmodifiableLazyStringList(
              callLetters_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.callLetters_ = callLetters_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.chinagps.gateway.buff.InnerDataBuff.Units) {
          return mergeFrom((cc.chinagps.gateway.buff.InnerDataBuff.Units)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.chinagps.gateway.buff.InnerDataBuff.Units other) {
        if (other == cc.chinagps.gateway.buff.InnerDataBuff.Units.getDefaultInstance()) return this;
        if (!other.callLetters_.isEmpty()) {
          if (callLetters_.isEmpty()) {
            callLetters_ = other.callLetters_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCallLettersIsMutable();
            callLetters_.addAll(other.callLetters_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.chinagps.gateway.buff.InnerDataBuff.Units parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.chinagps.gateway.buff.InnerDataBuff.Units) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string callLetters = 1;
      private com.google.protobuf.LazyStringList callLetters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCallLettersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          callLetters_ = new com.google.protobuf.LazyStringArrayList(callLetters_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string callLetters = 1;</code>
       *
       * <pre>
       *车辆列表
       * </pre>
       */
      public java.util.List<java.lang.String>
          getCallLettersList() {
        return java.util.Collections.unmodifiableList(callLetters_);
      }
      /**
       * <code>repeated string callLetters = 1;</code>
       *
       * <pre>
       *车辆列表
       * </pre>
       */
      public int getCallLettersCount() {
        return callLetters_.size();
      }
      /**
       * <code>repeated string callLetters = 1;</code>
       *
       * <pre>
       *车辆列表
       * </pre>
       */
      public java.lang.String getCallLetters(int index) {
        return callLetters_.get(index);
      }
      /**
       * <code>repeated string callLetters = 1;</code>
       *
       * <pre>
       *车辆列表
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCallLettersBytes(int index) {
        return callLetters_.getByteString(index);
      }
      /**
       * <code>repeated string callLetters = 1;</code>
       *
       * <pre>
       *车辆列表
       * </pre>
       */
      public Builder setCallLetters(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCallLettersIsMutable();
        callLetters_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string callLetters = 1;</code>
       *
       * <pre>
       *车辆列表
       * </pre>
       */
      public Builder addCallLetters(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCallLettersIsMutable();
        callLetters_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string callLetters = 1;</code>
       *
       * <pre>
       *车辆列表
       * </pre>
       */
      public Builder addAllCallLetters(
          java.lang.Iterable<java.lang.String> values) {
        ensureCallLettersIsMutable();
        super.addAll(values, callLetters_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string callLetters = 1;</code>
       *
       * <pre>
       *车辆列表
       * </pre>
       */
      public Builder clearCallLetters() {
        callLetters_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string callLetters = 1;</code>
       *
       * <pre>
       *车辆列表
       * </pre>
       */
      public Builder addCallLettersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCallLettersIsMutable();
        callLetters_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:seggateway.Units)
    }

    static {
      defaultInstance = new Units(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:seggateway.Units)
  }

  public interface UnitOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string callLetter = 1;
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车台呼号
     * </pre>
     */
    boolean hasCallLetter();
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车台呼号
     * </pre>
     */
    java.lang.String getCallLetter();
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车台呼号
     * </pre>
     */
    com.google.protobuf.ByteString
        getCallLetterBytes();
  }
  /**
   * Protobuf type {@code seggateway.Unit}
   *
   * <pre>
   **
   *  车辆
   * </pre>
   */
  public static final class Unit extends
      com.google.protobuf.GeneratedMessage
      implements UnitOrBuilder {
    // Use Unit.newBuilder() to construct.
    private Unit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Unit(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Unit defaultInstance;
    public static Unit getDefaultInstance() {
      return defaultInstance;
    }

    public Unit getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Unit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      //int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              callLetter_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Unit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Unit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.chinagps.gateway.buff.InnerDataBuff.Unit.class, cc.chinagps.gateway.buff.InnerDataBuff.Unit.Builder.class);
    }

    public static com.google.protobuf.Parser<Unit> PARSER =
        new com.google.protobuf.AbstractParser<Unit>() {
      public Unit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Unit(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Unit> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string callLetter = 1;
    public static final int CALLLETTER_FIELD_NUMBER = 1;
    private java.lang.Object callLetter_;
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车台呼号
     * </pre>
     */
    public boolean hasCallLetter() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车台呼号
     * </pre>
     */
    public java.lang.String getCallLetter() {
      java.lang.Object ref = callLetter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          callLetter_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string callLetter = 1;</code>
     *
     * <pre>
     *车台呼号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCallLetterBytes() {
      java.lang.Object ref = callLetter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callLetter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      callLetter_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCallLetter()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCallLetterBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCallLetterBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.chinagps.gateway.buff.InnerDataBuff.Unit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Unit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Unit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Unit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Unit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Unit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Unit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Unit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Unit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Unit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.chinagps.gateway.buff.InnerDataBuff.Unit prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code seggateway.Unit}
     *
     * <pre>
     **
     *  车辆
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cc.chinagps.gateway.buff.InnerDataBuff.UnitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Unit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Unit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.chinagps.gateway.buff.InnerDataBuff.Unit.class, cc.chinagps.gateway.buff.InnerDataBuff.Unit.Builder.class);
      }

      // Construct using cc.chinagps.gateway.buff.InnerDataBuff.Unit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        callLetter_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Unit_descriptor;
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.Unit getDefaultInstanceForType() {
        return cc.chinagps.gateway.buff.InnerDataBuff.Unit.getDefaultInstance();
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.Unit build() {
        cc.chinagps.gateway.buff.InnerDataBuff.Unit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.Unit buildPartial() {
        cc.chinagps.gateway.buff.InnerDataBuff.Unit result = new cc.chinagps.gateway.buff.InnerDataBuff.Unit(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.callLetter_ = callLetter_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.chinagps.gateway.buff.InnerDataBuff.Unit) {
          return mergeFrom((cc.chinagps.gateway.buff.InnerDataBuff.Unit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.chinagps.gateway.buff.InnerDataBuff.Unit other) {
        if (other == cc.chinagps.gateway.buff.InnerDataBuff.Unit.getDefaultInstance()) return this;
        if (other.hasCallLetter()) {
          bitField0_ |= 0x00000001;
          callLetter_ = other.callLetter_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCallLetter()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.chinagps.gateway.buff.InnerDataBuff.Unit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.chinagps.gateway.buff.InnerDataBuff.Unit) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string callLetter = 1;
      private java.lang.Object callLetter_ = "";
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车台呼号
       * </pre>
       */
      public boolean hasCallLetter() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车台呼号
       * </pre>
       */
      public java.lang.String getCallLetter() {
        java.lang.Object ref = callLetter_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          callLetter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车台呼号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCallLetterBytes() {
        java.lang.Object ref = callLetter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          callLetter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车台呼号
       * </pre>
       */
      public Builder setCallLetter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        callLetter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车台呼号
       * </pre>
       */
      public Builder clearCallLetter() {
        bitField0_ = (bitField0_ & ~0x00000001);
        callLetter_ = getDefaultInstance().getCallLetter();
        onChanged();
        return this;
      }
      /**
       * <code>required string callLetter = 1;</code>
       *
       * <pre>
       *车台呼号
       * </pre>
       */
      public Builder setCallLetterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        callLetter_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:seggateway.Unit)
    }

    static {
      defaultInstance = new Unit(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:seggateway.Unit)
  }

  public interface MapEntryOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string key = 1;
    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // required string value = 2;
    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code seggateway.MapEntry}
   *
   * <pre>
   **
   *  MapEntry
   * </pre>
   */
  public static final class MapEntry extends
      com.google.protobuf.GeneratedMessage
      implements MapEntryOrBuilder {
    // Use MapEntry.newBuilder() to construct.
    private MapEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MapEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MapEntry defaultInstance;
    public static MapEntry getDefaultInstance() {
      return defaultInstance;
    }

    public MapEntry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MapEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      //int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_MapEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_MapEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.class, cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder.class);
    }

    public static com.google.protobuf.Parser<MapEntry> PARSER =
        new com.google.protobuf.AbstractParser<MapEntry>() {
      public MapEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapEntry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MapEntry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.chinagps.gateway.buff.InnerDataBuff.MapEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code seggateway.MapEntry}
     *
     * <pre>
     **
     *  MapEntry
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cc.chinagps.gateway.buff.InnerDataBuff.MapEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_MapEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_MapEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.class, cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder.class);
      }

      // Construct using cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_MapEntry_descriptor;
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.MapEntry getDefaultInstanceForType() {
        return cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.getDefaultInstance();
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.MapEntry build() {
        cc.chinagps.gateway.buff.InnerDataBuff.MapEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.MapEntry buildPartial() {
        cc.chinagps.gateway.buff.InnerDataBuff.MapEntry result = new cc.chinagps.gateway.buff.InnerDataBuff.MapEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.chinagps.gateway.buff.InnerDataBuff.MapEntry) {
          return mergeFrom((cc.chinagps.gateway.buff.InnerDataBuff.MapEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.chinagps.gateway.buff.InnerDataBuff.MapEntry other) {
        if (other == cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.chinagps.gateway.buff.InnerDataBuff.MapEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.chinagps.gateway.buff.InnerDataBuff.MapEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // required string value = 2;
      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:seggateway.MapEntry)
    }

    static {
      defaultInstance = new MapEntry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:seggateway.MapEntry)
  }

  public interface StatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .seggateway.MapEntry infos = 1;
    /**
     * <code>repeated .seggateway.MapEntry infos = 1;</code>
     *
     * <pre>
     *状态信息
     * </pre>
     */
    java.util.List<cc.chinagps.gateway.buff.InnerDataBuff.MapEntry> 
        getInfosList();
    /**
     * <code>repeated .seggateway.MapEntry infos = 1;</code>
     *
     * <pre>
     *状态信息
     * </pre>
     */
    cc.chinagps.gateway.buff.InnerDataBuff.MapEntry getInfos(int index);
    /**
     * <code>repeated .seggateway.MapEntry infos = 1;</code>
     *
     * <pre>
     *状态信息
     * </pre>
     */
    int getInfosCount();
    /**
     * <code>repeated .seggateway.MapEntry infos = 1;</code>
     *
     * <pre>
     *状态信息
     * </pre>
     */
    java.util.List<? extends cc.chinagps.gateway.buff.InnerDataBuff.MapEntryOrBuilder> 
        getInfosOrBuilderList();
    /**
     * <code>repeated .seggateway.MapEntry infos = 1;</code>
     *
     * <pre>
     *状态信息
     * </pre>
     */
    cc.chinagps.gateway.buff.InnerDataBuff.MapEntryOrBuilder getInfosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code seggateway.Status}
   *
   * <pre>
   **
   *  状态
   * </pre>
   */
  public static final class Status extends
      com.google.protobuf.GeneratedMessage
      implements StatusOrBuilder {
    // Use Status.newBuilder() to construct.
    private Status(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Status(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Status defaultInstance;
    public static Status getDefaultInstance() {
      return defaultInstance;
    }

    public Status getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Status(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                infos_ = new java.util.ArrayList<cc.chinagps.gateway.buff.InnerDataBuff.MapEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              infos_.add(input.readMessage(cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          infos_ = java.util.Collections.unmodifiableList(infos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Status_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Status_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.chinagps.gateway.buff.InnerDataBuff.Status.class, cc.chinagps.gateway.buff.InnerDataBuff.Status.Builder.class);
    }

    public static com.google.protobuf.Parser<Status> PARSER =
        new com.google.protobuf.AbstractParser<Status>() {
      public Status parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Status(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Status> getParserForType() {
      return PARSER;
    }

    // repeated .seggateway.MapEntry infos = 1;
    public static final int INFOS_FIELD_NUMBER = 1;
    private java.util.List<cc.chinagps.gateway.buff.InnerDataBuff.MapEntry> infos_;
    /**
     * <code>repeated .seggateway.MapEntry infos = 1;</code>
     *
     * <pre>
     *状态信息
     * </pre>
     */
    public java.util.List<cc.chinagps.gateway.buff.InnerDataBuff.MapEntry> getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated .seggateway.MapEntry infos = 1;</code>
     *
     * <pre>
     *状态信息
     * </pre>
     */
    public java.util.List<? extends cc.chinagps.gateway.buff.InnerDataBuff.MapEntryOrBuilder> 
        getInfosOrBuilderList() {
      return infos_;
    }
    /**
     * <code>repeated .seggateway.MapEntry infos = 1;</code>
     *
     * <pre>
     *状态信息
     * </pre>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated .seggateway.MapEntry infos = 1;</code>
     *
     * <pre>
     *状态信息
     * </pre>
     */
    public cc.chinagps.gateway.buff.InnerDataBuff.MapEntry getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated .seggateway.MapEntry infos = 1;</code>
     *
     * <pre>
     *状态信息
     * </pre>
     */
    public cc.chinagps.gateway.buff.InnerDataBuff.MapEntryOrBuilder getInfosOrBuilder(
        int index) {
      return infos_.get(index);
    }

    private void initFields() {
      infos_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getInfosCount(); i++) {
        if (!getInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < infos_.size(); i++) {
        output.writeMessage(1, infos_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < infos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, infos_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cc.chinagps.gateway.buff.InnerDataBuff.Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Status parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Status parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cc.chinagps.gateway.buff.InnerDataBuff.Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cc.chinagps.gateway.buff.InnerDataBuff.Status prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code seggateway.Status}
     *
     * <pre>
     **
     *  状态
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cc.chinagps.gateway.buff.InnerDataBuff.StatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Status_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Status_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.chinagps.gateway.buff.InnerDataBuff.Status.class, cc.chinagps.gateway.buff.InnerDataBuff.Status.Builder.class);
      }

      // Construct using cc.chinagps.gateway.buff.InnerDataBuff.Status.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          infosBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.chinagps.gateway.buff.InnerDataBuff.internal_static_seggateway_Status_descriptor;
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.Status getDefaultInstanceForType() {
        return cc.chinagps.gateway.buff.InnerDataBuff.Status.getDefaultInstance();
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.Status build() {
        cc.chinagps.gateway.buff.InnerDataBuff.Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cc.chinagps.gateway.buff.InnerDataBuff.Status buildPartial() {
        cc.chinagps.gateway.buff.InnerDataBuff.Status result = new cc.chinagps.gateway.buff.InnerDataBuff.Status(this);
        //int from_bitField0_ = bitField0_;
        if (infosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            infos_ = java.util.Collections.unmodifiableList(infos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.infos_ = infos_;
        } else {
          result.infos_ = infosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.chinagps.gateway.buff.InnerDataBuff.Status) {
          return mergeFrom((cc.chinagps.gateway.buff.InnerDataBuff.Status)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.chinagps.gateway.buff.InnerDataBuff.Status other) {
        if (other == cc.chinagps.gateway.buff.InnerDataBuff.Status.getDefaultInstance()) return this;
        if (infosBuilder_ == null) {
          if (!other.infos_.isEmpty()) {
            if (infos_.isEmpty()) {
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInfosIsMutable();
              infos_.addAll(other.infos_);
            }
            onChanged();
          }
        } else {
          if (!other.infos_.isEmpty()) {
            if (infosBuilder_.isEmpty()) {
              infosBuilder_.dispose();
              infosBuilder_ = null;
              infos_ = other.infos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              infosBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfosFieldBuilder() : null;
            } else {
              infosBuilder_.addAllMessages(other.infos_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getInfosCount(); i++) {
          if (!getInfos(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cc.chinagps.gateway.buff.InnerDataBuff.Status parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cc.chinagps.gateway.buff.InnerDataBuff.Status) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .seggateway.MapEntry infos = 1;
      private java.util.List<cc.chinagps.gateway.buff.InnerDataBuff.MapEntry> infos_ =
        java.util.Collections.emptyList();
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          infos_ = new java.util.ArrayList<cc.chinagps.gateway.buff.InnerDataBuff.MapEntry>(infos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cc.chinagps.gateway.buff.InnerDataBuff.MapEntry, cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder, cc.chinagps.gateway.buff.InnerDataBuff.MapEntryOrBuilder> infosBuilder_;

      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public java.util.List<cc.chinagps.gateway.buff.InnerDataBuff.MapEntry> getInfosList() {
        if (infosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(infos_);
        } else {
          return infosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public int getInfosCount() {
        if (infosBuilder_ == null) {
          return infos_.size();
        } else {
          return infosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public cc.chinagps.gateway.buff.InnerDataBuff.MapEntry getInfos(int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);
        } else {
          return infosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public Builder setInfos(
          int index, cc.chinagps.gateway.buff.InnerDataBuff.MapEntry value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.set(index, value);
          onChanged();
        } else {
          infosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public Builder setInfos(
          int index, cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.set(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public Builder addInfos(cc.chinagps.gateway.buff.InnerDataBuff.MapEntry value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(value);
          onChanged();
        } else {
          infosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public Builder addInfos(
          int index, cc.chinagps.gateway.buff.InnerDataBuff.MapEntry value) {
        if (infosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfosIsMutable();
          infos_.add(index, value);
          onChanged();
        } else {
          infosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public Builder addInfos(
          cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public Builder addInfos(
          int index, cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder builderForValue) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.add(index, builderForValue.build());
          onChanged();
        } else {
          infosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public Builder addAllInfos(
          java.lang.Iterable<? extends cc.chinagps.gateway.buff.InnerDataBuff.MapEntry> values) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          super.addAll(values, infos_);
          onChanged();
        } else {
          infosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public Builder clearInfos() {
        if (infosBuilder_ == null) {
          infos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          infosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public Builder removeInfos(int index) {
        if (infosBuilder_ == null) {
          ensureInfosIsMutable();
          infos_.remove(index);
          onChanged();
        } else {
          infosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder getInfosBuilder(
          int index) {
        return getInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public cc.chinagps.gateway.buff.InnerDataBuff.MapEntryOrBuilder getInfosOrBuilder(
          int index) {
        if (infosBuilder_ == null) {
          return infos_.get(index);  } else {
          return infosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public java.util.List<? extends cc.chinagps.gateway.buff.InnerDataBuff.MapEntryOrBuilder> 
           getInfosOrBuilderList() {
        if (infosBuilder_ != null) {
          return infosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(infos_);
        }
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder addInfosBuilder() {
        return getInfosFieldBuilder().addBuilder(
            cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder addInfosBuilder(
          int index) {
        return getInfosFieldBuilder().addBuilder(
            index, cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .seggateway.MapEntry infos = 1;</code>
       *
       * <pre>
       *状态信息
       * </pre>
       */
      public java.util.List<cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder> 
           getInfosBuilderList() {
        return getInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cc.chinagps.gateway.buff.InnerDataBuff.MapEntry, cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder, cc.chinagps.gateway.buff.InnerDataBuff.MapEntryOrBuilder> 
          getInfosFieldBuilder() {
        if (infosBuilder_ == null) {
          infosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cc.chinagps.gateway.buff.InnerDataBuff.MapEntry, cc.chinagps.gateway.buff.InnerDataBuff.MapEntry.Builder, cc.chinagps.gateway.buff.InnerDataBuff.MapEntryOrBuilder>(
                  infos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          infos_ = null;
        }
        return infosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:seggateway.Status)
    }

    static {
      defaultInstance = new Status(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:seggateway.Status)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_seggateway_Units_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_seggateway_Units_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_seggateway_Unit_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_seggateway_Unit_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_seggateway_MapEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_seggateway_MapEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_seggateway_Status_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_seggateway_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017InnerData.proto\022\nseggateway\"\034\n\005Units\022\023" +
      "\n\013callLetters\030\001 \003(\t\"\032\n\004Unit\022\022\n\ncallLette" +
      "r\030\001 \002(\t\"&\n\010MapEntry\022\013\n\003key\030\001 \002(\t\022\r\n\005valu" +
      "e\030\002 \002(\t\"-\n\006Status\022#\n\005infos\030\001 \003(\0132\024.segga" +
      "teway.MapEntryB)\n\030cc.chinagps.gateway.bu" +
      "ffB\rInnerDataBuff"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_seggateway_Units_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_seggateway_Units_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_seggateway_Units_descriptor,
              new java.lang.String[] { "CallLetters", });
          internal_static_seggateway_Unit_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_seggateway_Unit_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_seggateway_Unit_descriptor,
              new java.lang.String[] { "CallLetter", });
          internal_static_seggateway_MapEntry_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_seggateway_MapEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_seggateway_MapEntry_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_seggateway_Status_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_seggateway_Status_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_seggateway_Status_descriptor,
              new java.lang.String[] { "Infos", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
